------------------//VARIABLES
local AnimeJJK = {
	worldId = "JJK",
	displayName = "Jujutsu Kaisen",
	initialUpgradeState = {
		stage = 0,
		storyRuns = 0,
		unlockedRepeatables = {"LookAround", "CryLoudly", "Sleep"},
		removedRepeatables = {},
		repeatableSlotCap = 3,
		chapterFlags = {},
		upgradeFlags = {},
		permanent = {
			cursedBody = 0,
			cursedControl = 0,
			cooldownFocus = 0,
			CursedPerceptionI = 0,
			BreathControl = 0,
			CursedFlowI = 0,
			BodyReinforcementI = 0,
			CombatInstinct = 0,
			SimpleBarrierI = 0,
			CursedToolI = 0,
			BodyMindCycle = 0,
			MentalResistanceI = 0,
			SimpleBarrierII = 0,
			CounterDomain = 0,
			ReverseTechniqueI = 0,
			UnstableRegeneration = 0,
			PersonalDomainIncomplete = 0,
			PartialExpansion = 0,
		},
	},
	repeatableOrder = {
		"LookAround",
		"CryLoudly",
		"Sleep",
		"WiggleAround",
		"ObserveResidue",
		"BasicTraining",
		"WanderHalls",
		"ReadCursedNotes",
		"PatrolArea",
		"TradeFragments",
		"ProperMeal",
		"FocusMeditation",
		"CursedConditioning",
		"ShadowDrill",
		"ExorciseGrade4",
		"InterrogateCultist",
		"StudyRitualPatterns",
		"MapDistortion",
		"ReversePractice",
		"StabilizeDomain",
		"HuntSpecialGrade",
		"RepairTheCity",
		"TrainSuccessor",
		"EnterBrokenVeil",
	},
	equipmentSlots = {
		"head",
		"neck",
		"shirt",
		"pants",
		"weapon",
		"enchantment",
	},
	upgrades = {
		cursedBody = {
			maxLevel = 10,
			baseSoulCost = 75,
			shardCostEvery = 5,
			hpPerLevel = 5,
			defPerLevel = 0.75,
		},
		cursedControl = {
			maxLevel = 10,
			baseSoulCost = 90,
			shardCostEvery = 5,
			atkPerLevel = 1,
			curseEnergyPerLevel = 3,
		},
		cooldownFocus = {
			maxLevel = 5,
			baseSoulCost = 150,
			shardCostEvery = 3,
			speedPerLevel = 0.5,
			cooldownReductionPerLevel = 0.03,
		},
		CursedPerceptionI = {
			maxLevel = 1,
			baseSoulCost = 200,
			shardCostEvery = 0,
			luckPerLevel = 0.35,
		},
		BreathControl = {
			maxLevel = 1,
			baseSoulCost = 250,
			shardCostEvery = 0,
			hpPerLevel = 6,
			maxStaminaPerLevel = 1,
		},
		CursedFlowI = {
			maxLevel = 1,
			baseSoulCost = 300,
			shardCostEvery = 0,
			atkPerLevel = 1,
			curseEnergyPerLevel = 5,
		},
		BodyReinforcementI = {
			maxLevel = 1,
			baseSoulCost = 320,
			shardCostEvery = 0,
			hpPerLevel = 12,
			defPerLevel = 1,
			maxStaminaPerLevel = 1,
		},
		CombatInstinct = {
			maxLevel = 1,
			baseSoulCost = 350,
			shardCostEvery = 0,
			atkPerLevel = 1.2,
			speedPerLevel = 0.4,
			luckPerLevel = 0.2,
		},
		SimpleBarrierI = {
			maxLevel = 1,
			baseSoulCost = 380,
			shardCostEvery = 0,
			defPerLevel = 1.6,
			hpPerLevel = 8,
		},
		CursedToolI = {
			maxLevel = 1,
			baseSoulCost = 420,
			shardCostEvery = 0,
			atkPerLevel = 2,
			luckPerLevel = 0.15,
		},
		BodyMindCycle = {
			maxLevel = 1,
			baseSoulCost = 460,
			shardCostEvery = 0,
			maxStaminaPerLevel = 1,
			hpPerLevel = 5,
		},
		MentalResistanceI = {
			maxLevel = 1,
			baseSoulCost = 500,
			shardCostEvery = 0,
			defPerLevel = 1,
			speedPerLevel = 0.2,
		},
		SimpleBarrierII = {
			maxLevel = 1,
			baseSoulCost = 540,
			shardCostEvery = 0,
			defPerLevel = 2,
			hpPerLevel = 12,
		},
		CounterDomain = {
			maxLevel = 1,
			baseSoulCost = 580,
			shardCostEvery = 0,
			atkPerLevel = 1.5,
			defPerLevel = 1,
		},
		ReverseTechniqueI = {
			maxLevel = 1,
			baseSoulCost = 620,
			shardCostEvery = 0,
			hpPerLevel = 10,
			maxStaminaPerLevel = 1,
		},
		UnstableRegeneration = {
			maxLevel = 1,
			baseSoulCost = 640,
			shardCostEvery = 0,
			hpPerLevel = 8,
			defPerLevel = 0.8,
		},
		PersonalDomainIncomplete = {
			maxLevel = 1,
			baseSoulCost = 700,
			shardCostEvery = 0,
			atkPerLevel = 2,
			defPerLevel = 1.2,
			curseEnergyPerLevel = 8,
		},
		PartialExpansion = {
			maxLevel = 1,
			baseSoulCost = 780,
			shardCostEvery = 0,
			atkPerLevel = 3,
			defPerLevel = 1.5,
			speedPerLevel = 0.5,
			luckPerLevel = 0.5,
		},
	},
}

------------------//INIT
return AnimeJJK
