------------------//VARIABLES
local GameConfig = {
	DATA_VERSION = 3,
	LEVEL_CAP = 600,
	AUTO_SAVE_SECONDS = 60,
	ACTION_TICK_SECONDS = 1,
	MIN_TRAIN_INTERVAL = 0.12,
	CULTIVATE_STAMINA_COST = 1,
	CULTIVATE_KNOWLEDGE_GAIN = 1,
	TRAIN_EXP_PER_TICK = 5,
	TRAIN_STAMINA_COST = 1,
	TRAIN_ATK_PER_TICK = 0.1,
	TRAIN_DEF_PER_TICK = 0.05,
	TRAIN_SPD_PER_TICK = 0.03,
	TRAIN_HP_PER_TICK = 0.2,
	TRAIN_WORLD_SOULS_PER_10_TAPS = 1,
	IDLE_EXP_PER_MINUTE = 60,
	FOCUS_MAX = 100,
	FOCUS_PER_TAP = 1,
	FOCUS_BURST_SECONDS = 10,
	FOCUS_BURST_MULTIPLIER = 2,
	CULTIVATE_QI_PER_TICK = 4,
	JJK_CURSE_ENERGY_PER_TAP = 2,
	JJK_CURSE_ENERGY_PASSIVE_PER_10_SECONDS = 2,
	JJK_BACKLASH_MAX_HP_PERCENT = 0.08,
	JJK_OVERFLOW_MIN = 75,
	JJK_OVERFLOW_EXP_BONUS = 0.1,
	RESOURCE_MAX = 10,
	STAMINA_MAX = 10,
	REST_STAMINA_PER_TICK = 1,
	WORK_STAMINA_COST = 2,
	WORK_GOLD_GAIN = 5,
	EXPLORE_STAMINA_COST = 2,
	EXPLORE_KNOWLEDGE_GAIN = 1,
	EXPLORE_GOLD_GAIN = 2,
	BREAKTHROUGH_BASE_CHANCE = 0.65,
	BREAKTHROUGH_QI_LOSS_LIGHT = 0.35,
	BREAKTHROUGH_QI_LOSS_HEAVY = 0.65,
	BATTLE_EXP_GAIN = 12,
	BATTLE_SOULS_GAIN = 1,
	BATTLE_STAMINA_COST = 1,
	MANUAL_BATTLE_EXP_BONUS = 0.1,
	PROTECTOR_QUEST_EXP_BONUS = 0.15,
	CONQUEROR_BATTLE_EXP_BONUS = 0.2,
	MAX_REBIRTHS = 5,
	LORE_LOGS_PER_WORLD = 20,
	REALM_NAMES = {
		"Mortal",
		"Qi Gathering",
		"Foundation",
		"Core Formation",
		"Nascent Soul",
		"Immortal",
	},
	BATTLE_TIERS = {
		{
			tier = 1,
			levelGate = 1,
			expMultiplier = 1,
			souls = 5,
			baseHp = 35,
			baseAtk = 7,
			baseDef = 3,
			jjkEnemy = "Grade 4 Cursed Spirit",
			narutoEnemy = "Academy Student",
			onePieceEnemy = "Sea Bandit",
		},
		{
			tier = 2,
			levelGate = 20,
			expMultiplier = 2.5,
			souls = 12,
			baseHp = 120,
			baseAtk = 18,
			baseDef = 12,
			jjkEnemy = "Grade 3 Cursed Spirit",
			narutoEnemy = "Genin",
			onePieceEnemy = "East Blue Pirate",
		},
		{
			tier = 3,
			levelGate = 75,
			expMultiplier = 5,
			souls = 28,
			baseHp = 420,
			baseAtk = 44,
			baseDef = 35,
			jjkEnemy = "Grade 2 Cursed Spirit",
			narutoEnemy = "Chunin",
			onePieceEnemy = "Grand Line Rookie",
		},
		{
			tier = 4,
			levelGate = 200,
			expMultiplier = 10,
			souls = 70,
			baseHp = 1450,
			baseAtk = 120,
			baseDef = 90,
			jjkEnemy = "Grade 1 Cursed Spirit",
			narutoEnemy = "Jonin",
			onePieceEnemy = "Warlord-tier",
		},
		{
			tier = 5,
			levelGate = 400,
			expMultiplier = 20,
			souls = 180,
			baseHp = 5200,
			baseAtk = 280,
			baseDef = 180,
			jjkEnemy = "Special Grade",
			narutoEnemy = "Kage-level",
			onePieceEnemy = "Admiral-tier",
		},
	},
	STORY_MILESTONES = {
		{level = 1, questId = "FirstBreath", title = "The Chosen"},
		{level = 25, questId = "TheAwakening", title = "The Awakened"},
		{level = 50, questId = "NameKnown", title = "The Known"},
		{level = 100, questId = "TheTrial", title = "The Proven"},
		{level = 300, questId = "HeavensResistance", title = "The Unstoppable"},
		{level = 500, questId = "Immortal", title = "The Immortal"},
	},
	RIVAL_LEVELS = {20, 75, 200, 400},
	REBIRTH_MULTIPLIERS = {1.1, 1.15, 1.2, 1.25, 1.3},
	REBIRTH_TITLES = {
		"The Reborn",
		"Twice Immortal",
		"The Undying",
		"Heaven's Defect",
		"True Immortal",
	},
	LOGIN_REWARDS = {
		{exp = 500},
		{worldSouls = 100},
		{boostId = "ExpBoost15", boostSeconds = 1800, expMultiplier = 1.5},
		{title = "Aura Fragment"},
		{boostId = "ExpBoost20", boostSeconds = 3600, expMultiplier = 2},
		{item = "World Outfit Accent"},
		{rebirthShards = 1},
	},
	SHOP_ITEMS = {
		SmallExpPotion = {price = 100, exp = 500, dailyLimit = 10},
		MediumExpPotion = {price = 350, exp = 2000, dailyLimit = 5},
		LargeExpPotion = {price = 1200, exp = 10000, dailyLimit = 2},
		StatBoostPill = {price = 500, boostSeconds = 1800, statMultiplier = 1.1, dailyLimit = 3},
		CooldownReset = {price = 200, resetCooldowns = true, dailyLimit = 3},
		FocusCharge = {price = 150, focusCharge = true, dailyLimit = 5},
		BattleRevive = {price = 300, battleRevive = true, dailyLimit = 2},
	},
}

------------------//INIT
return GameConfig
