------------------//VARIABLES
local GameConfig = {
	DATA_VERSION = 1,
	LEVEL_CAP = 600,
	AUTO_SAVE_SECONDS = 60,
	MIN_TRAIN_INTERVAL = 0.12,
	TRAIN_EXP_PER_TAP = 5,
	TRAIN_ATK_PER_TAP = 0.1,
	TRAIN_DEF_PER_TAP = 0.05,
	FOCUS_MAX = 100,
	FOCUS_PER_TAP = 1,
	FOCUS_BURST_SECONDS = 10,
	FOCUS_BURST_MULTIPLIER = 2,
	JJK_CURSE_ENERGY_PER_TAP = 2,
	JJK_OVERFLOW_MIN = 75,
	JJK_OVERFLOW_EXP_BONUS = 0.1,
	RESOURCE_MAX = 10,
	CULTIVATE_STAMINA_COST = 1,
	CULTIVATE_KNOWLEDGE_GAIN = 0.1,
	BATTLE_EXP_GAIN = 12,
	BATTLE_SOULS_GAIN = 1,
}

------------------//INIT
return GameConfig
